version: "3.8"

services:
  nginx:
    build:
      context: ./docker
    container_name: devops-nginx
    ports:
      - "8080:80"
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

    volumes:
      - nginx_logs:/var/log/nginx

    networks:
      - devops-network

networks:
  devops-network:
    driver: bridge

volumes:
  nginx_logs: